<div align="justify"><h2>HIPAA Form</h2><br>
PATIENT PRIVACY ACT<br><br>

This notice describes how chiropractic and medical information about you may be used and disclosed and how you can get access to this information. Please review it carefully. In the course of your case as a patient with Up 2 Speed Sports Performance and Therapy we may use or disclose personal information about you in the following ways: -Your protected health information, including your clinical records, may be disclosed to another health provider or hospital if it is necessary to refer you for further diagnosis, assessment, or treatment. -Your health care records as well as your billing records may be disclosed to another party, such as an insurance carrier, an HMO, a PPO, or your employer, if they are or may be responsible for payment of services provided to you. -Your name, address, phone number, and your health records may be used to contact you regarding appointment reminders, information about alternatives to your present care, or other health related information that may be of interest to you. You have the right to request restrictions on our use of your protected health information for treatment, payment, or operation purposes. Such requests are not automatic and require the agreement of this office. I understand that this office uses an open treatment area and I may be treated in front on other patients. I may request a private room to be used for my treatment. Health information or information about my case may be discussed in front of the other chiropractors in the office or the office receptionist. A private room can be requested to discuss any health information about yourself. If you are not at home to receive an appointment reminder or other related information, a message may be left on your answering machine or with a person in your household. You have the right to confidential communications and to request restrictions relative to such contacts. You also have the right to be contacted by alternative means or at alternative locations. We are permitted/may be required to use or disclose your health information without your authorization in these following circumstances: -If we provide health care services to you in an emergency. -If we are required by law to provide care to and we are unable to obtain your consent after attempting to do so. -If there are substantial barriers to communicating with you, but in our professional judgement, we believe that you intend for us to provide care. -If we are ordered by courts or another appropriate agency. You have the right to receive an accounting of any such disclosures made by this office. Any use or disclosure of your protected health information, other than as outlined above, will only be made upon your written authorization. If you provide an authorization for release of information you have the right to revoke that authorization at a later date. <br><br>

PRIVACY NOTICE Information that we use or disclose based on this privacy notice may be subject to re-disclosure by the person to whom we provided the information and may no longer be protected by federal privacy rules. We normally provide information about your health to you in person at the time you receive chiropractic care from us. We may also mail information to you regarding your health care or about the status of your account. If you would like to receive this information in a specific form, please advise us in writing as to your preference. You have the right to inspect and/or copy your health information for as long as the information remains in our files. In addition, you have the right to request an amendment to your health information. Request to inspect, copy, or amend your health related information should be provided to us in writing. We are required by state and federal law to maintain the privacy of your patient file and health protected information therein. We are also required to provide you with this notice of our privacy practices with respect to your health information. We are further required by law to abide by the terms of this notice while it is in effect. If you would like further information or have a complaint regarding our privacy notice, our privacy practice, or any aspect of private activities, you should direct your complaints to: Dr. Michael A. Sanchez, D.C. You also have the right to log a complaint with the Secretary of Department of Health and Human Services. If you choose to log a complaint with this office or with the Secretary, your care will continue and not be disadvantaged by this office or our staff in any manner whatsoever. This notice is effective January 1, 2003. This notice and any alterations or amendments made herein will expire seven years after the date upon which the record was created. My signature acknowledges that I have received a copy of this notice. <br><br>
Do you consent to above PATIENT PRIVACY ACT? <br><br>
Date <input>
</div>
