<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    protected $fillable = [
        'firstname', 
        'middleinitial',
        'lastname',
        'street',
        'city',
        'zip',
        'state',
        'homephone',
        'workphone',
        'cellphone',
        'email',
        'dobmonth',
        'dobday',
        'dobyear',
        'ssn',
        'maritalstatus',
        'sex',
        'employer',
        'occupation',
        'status',
        'spouselastname',
        'spousefirstname',
        'spousessn',
        'spousedob',
        'emergencyname',
        'emergencyrelationship',
        'emergencyhomephone',
        'emergencycellphone',
        'password',
        'carriername',
        'insuredname',
        'claimsadjuster',
        'insureddob',
        'relationshiptoinsured',
        'policynumber',
        'groupnumber',
        'claimnumber',
        'phonenumber',
        'visitsauthorized',
        'visitsused',
        'insindeductible',
        'insoutdeductible',
        'insinremaining',
        'insincoinsuranc',
        'insoutcoinsurance',
        'insincopay',
        'insoutcopay',
        'insnotes',
        'preexisting',
        'Standing',
        'Sit_at_a_desk',
        'Work_on_a_computer',
        'Work_on_a_phone',
        'Moderate_Heavy_labor',
        'Stay_at_home',
        'Deliver_packages',
        'Retired',
        'Tobacco_Smoke',
        'Alcoholic_beverages',
        'Caffeine',
        'Exercise',
        'Mother',
        'Father',
        'Sisters',
        'Brothers',
        'Children',
        'nickname',
        'caseindicator',
        'status',
        'referredbytype',
        'paymenttype',
        'suffix',
        'coinsurance',
        'coinsurancedp',
        'alternateno',
        'pitype',
        'patientphoto',
        'language',
        'apptreminders',
        'carrier',
        'referredby',
        'referredbypatient',
        'costpervisit0',
        'costpervisit1',
        'paymenttype0',
        'paymenttype1',
        'network0',
        'network1',
        'copay0',
        'copay1',
        'coinsurance0',
        'coinsurance1',
        'coinsurancedp0',
        'coinsurancedp1'
    ];


    public function exam()
    {
        return $this->hasMany(examsrom::class);
    }
}
